version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - go
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore
      include: scope
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: docker
    directory: "/cmd/gateway"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: docker
    directory: "/cmd/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore
      include: scope
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
